schema_version: 1

context:
  name: azure-mgmt-policyinsights
  version: 1.1.0b4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-policyinsights-${{ version }}.zip
  sha256: 681d7ac72ae13581c97a2b6f742795fa48a4db50762c2fb9fce4834081b04e92

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - msrest >=0.7.1
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - typing-extensions >=4.3.0

tests:
  - python:
      imports:
        - azure.mgmt.policyinsights
        - azure.mgmt.policyinsights.aio
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Microsoft Azure Policy Insights Client Library for Python
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
