schema_version: 1

context:
  name: azure-mgmt-policyinsights
  version: 1.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-policyinsights-${{ version }}.zip
  sha256: 75103fb4541aeae30bb687dee1fedd9ca65530e6b97b2d9ea87f74816905202a

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - msrest >=0.5.0
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.2.0,<2.0.0

tests:
  - python:
      imports:
        - azure.mgmt.policyinsights
        - azure.mgmt.policyinsights.aio
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Microsoft Azure Policy Insights Client Library for Python
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
